spring:
  application:
    name: entity-framework
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5050/db
    password: pass
    username: user
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true